### ISSUE TITLE
Hi @dicy, request about your username

### ISSUE THREAD

**Issue by AlexDicy** [dr-dicy/astronomy#1]
Hi @dicy!
I have no idea if this is reaching your inbox in any way, but this is my hope.

Your account has been inactive for more than 9 years, I would love to be able to use the username "dicy" for a couple projects.

Please let me know if you are going to consider my request!

Regards,
Lorenzo

**Comment by dicy** [comment]
Hi,

That’s fine. I don’t ever use this account because I just have a work
account. Do I need to do something on my end to let you use the name? I
don’t really want to delete my account so maybe I can just change my
username?

**Comment by AlexDicy** [comment]
Hi, thank you for the fast response!

Yes, changing the username is enough for it to become available, there's no need to delete the account.

Thank you,
Lorenzo

**Comment by AlexDicy** [comment]
Thank you, I'm closing the issue
